export const products = [
    {
        id: 6001,
        fav: true,
        offer: true,
        img: "/images/slider-1.webp",
        sliderImg: [
            "/images/slider-1.webp",
            "/images/slider-2.webp",
            "/images/slider-3.webp",
            "/images/slider-3.webp",
        ],
        nameAR: "ميثيكوبال 500 مكجم فيتامين ب 12 30 قرص",
        brand: "غارنييه",
        rate: 3,
        price: 25.5,
        oldPrice: 29.5,
        available: true,
    },
    {
        id: 6002,
        fav: false,
        offer: false,
        img: "/images/product-3.webp",
        sliderImg: [
            "/images/slider-1-1.webp",
            "/images/slider-2-1.webp",
            "/images/slider-3-1.webp",
            "/images/slider-4-1.webp",
            "/images/slider-5-1.webp",
        ],
        nameAR: "بلسم بانتين هاير ساينس بالبيوتين، 475 مل",
        brand: "بانتين",
        rate: 4,
        price: 60.5,
        oldPrice: 69.5,
        available: false,
    },
    {
        id: 6003,
        fav: true,
        offer: true,
        img: "/images/product-3.webp",
        sliderImg: [
            "/images/slider-1-1.webp",
            "/images/slider-2-1.webp",
            "/images/slider-3-1.webp",
            "/images/slider-4-1.webp",
            "/images/slider-5-1.webp",
        ],
        nameAR: "بلسم بانتين هاير ساينس بالبيوتين، 475 مل",
        brand: "بانتين",
        rate: 5,
        price: 70.5,
        oldPrice: 99.5,
        available: true,
    },
    {
        id: 6000,
        fav: false,
        offer: true,
        img: "/images/slider-1-2.webp",
        sliderImg: [
            "/images/slider-1-2.webp",
            "/images/slider-2-2.webp",
            "/images/slider-3-2.webp",
            "/images/slider-1-2.webp",
        ],
        nameAR: "سكين دكتور انستانت فيس ليفت سيروم فورى 30 مل",
        brand: "سكين دوكترز",
        rate: 2,
        price: 180.5,
        oldPrice: 200,
        available: true,
    },
    {
        id: 6005,
        fav: true,
        offer: true,
        img: "/images/product-3.webp",
        sliderImg: [
            "/images/slider-1-1.webp",
            "/images/slider-2-1.webp",
            "/images/slider-3-1.webp",
            "/images/slider-4-1.webp",
            "/images/slider-5-1.webp",
        ],
        nameAR: "بلسم بانتين هاير ساينس بالبيوتين، 475 مل",
        brand: "بانتين",
        rate: 5,
        price: 70.5,
        oldPrice: 90,
        available: true,
    }
];
